### PR TITLE
Added localization support. Added English and Spanish catkey files

### PR DESCRIPTION
**Pull request by cafeina-software**
Proposed changes:

- Added localization support for translatable UI text strings in source code. Makefile was also updated to be able to generate catkeys and embed them with "make bindcatalogs".
- Added English and Spanish catkey files.

### CODE REVIEW

**Comment by humdingerb** [comment]
To fit better into Haiku's GUI, you may want to change the string to sentence casing ("This window of this application"), and use all caps "OK".
There are a few more strings to translate in MoeMascot.cpp. And a typo to correct there: "preferred". Twice.

When done we can add the app to Polyglot at http://i18n.kacperkasper.pl/projects

**Comment by cafeina-software** [comment]
@humdingerb I've done the requested changes. Please review them in case I missed something else. Thanks.

**Comment by humdingerb** [comment]
Looks good, thank you.
The one thing left is the About alert that gets its text from the .rdef file and is therefore not translatable. You should put the text directly in AboutRequested(). While at it, you may want to use the BAboutWindow class. I think you'll have to add
SYSTEM_INCLUDE_PATHS = /system/develop/headers/private/interface to the Makefile for that.

As examples for BAboutWindow, see other HaikuArchive projects, like MidiSynth.

**Comment by cafeina-software** [comment]
I've done the changes to the About box, using the BAboutWindow class in private headers. Also accordingly updated the catalogs to match the new strings. 

I left the original description text (app_version.long_info) in English in the .rdef file in case they have to be there for whatever reason. But that does not affect the description in About box, that now is translatable.

**Comment by humdingerb** [comment]
#include <AboutWindow.h> is missing from MoeApplication.cpp.
I think we should correct the info in the rdef and about window: "Moe is a program to place a cute mascot on the active window."
It would also be OK to add yourself to the authors in the about window or at least the headers of all the files you've touched with your contributions.

**Comment by humdingerb** [comment]
Very good, thanks! Let's merge and I'll add the catkeys to Polyglot.

**Pull request merged**
