### PR TITLE
Added Spanish translation of doc files 

### PR DESCRIPTION
**Pull request by cafeina-software**

### CODE REVIEW

**Comment by waddlesplash** [comment]
Thanks!

(PS. We could use some help translating Haiku proper into Spanish at https://i18n.haiku-os.org/pootle/ and https://i18n.haiku-os.org/userguide/ -- and that would be much more used than these odd apps [has anyone even used Moe recently?])

**Comment by cafeina-software** [comment]
I already have a pootle account there, but for some reason there I don't have any permission to submit translations or fix older ones.
There's an only user with permission to translate to Spanish, but I don't know if s/he's active or not.
It's not easy to collaborate when you can't submit translations directly.

**Comment by waddlesplash** [comment]
What's your account name? I can grant you permission to submit directly.

**Comment by fuckyourselfup** [comment]
it's zerabt

**Comment by cafeina-software** [comment]
cafeina

**Comment by waddlesplash** [comment]
Done.

**Pull request merged**
